// Generated by `bun init`

declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.mp3" {
  /**
   * A path to the MP3 file
   */
  const path: `${string}.mp3`;
  export = path;
}

declare module "*.wav" {
  /**
   * A path to the WAV file
   */
  const path: `${string}.wav`;
  export = path;
}

declare module "*.ogg" {
  /**
   * A path to the OGG file
   */
  const path: `${string}.ogg`;
  export = path;
}

declare module "*.jpg" {
  /**
   * A path to the JPG file
   */
  const path: `${string}.jpg`;
  export = path;
}

declare module "*.jpeg" {
  /**
   * A path to the JPEG file
   */
  const path: `${string}.jpeg`;
  export = path;
}

declare module "*.png" {
  /**
   * A path to the PNG file
   */
  const path: `${string}.png`;
  export = path;
}

declare module "*.webp" {
  /**
   * A path to the WebP file
   */
  const path: `${string}.webp`;
  export = path;
}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
